---
- name: remove packages
  apt:
    name:
      - nvidia-docker
      - nvidia-docker2
    state: absent
    autoremove: yes
    purge: yes

- name: add key
  apt_key:
    url: "{{ nvidia_docker_repo_gpg_url }}"
    state: present
  when: nvidia_docker_add_repo

- name: add repo
  get_url:
    url: "{{ nvidia_docker_repo_base_url }}/{{ _ubuntu_repo_dist_name }}/{{ _ubuntu_repo_file_name }}"
    dest: "{{ _ubuntu_repo_file_path }}"
    mode: 0644
    owner: root
    group: root
  when: nvidia_docker_add_repo

- name: install packages
  apt:
    name: nvidia-container-runtime
    state: present
    update_cache: yes
  notify: reload docker
